### PR TITLE
[Fix] Translate edit/create page browser tab title

### LINKED ISSUE #160: Tab title incorrect for edit profile
**Describe the bug**
When editing profile the browser tab title says "create Profile". It should say "edit profile"

**To Reproduce**
1. Go to "edit profile"
2. See browser tab title

**Expected behavior**
 It should say "edit profile" when editing profile and "create Profile" when creating the profile.

**Screenshots**
image

### PR DESCRIPTION
**Pull request by dynamic11**
- converted classes to functions for the create and edit profile page
- translate the tab titles for create/edit profile pages (closes #160)

### CODE REVIEW

File: services/frontend-v3/src/pages/ProfileEdit.jsx [hunk 1]
```diff
@@ -1,25 +1,19 @@
 import React from "react";
+import { injectIntl } from "react-intl";
 import EditProfileLayout from "../components/layouts/editProfileLayout/EditProfileLayout";
 
-class ProfileCreate extends React.Component {
-  goto = (link) => this.props.history.push(link);
+const ProfileCreate = (props) => {
```
Comment (BenJeau) [inline services/frontend-v3/src/pages/ProfileEdit.jsx]: Seems like it should be ProfileEdit instead of ProfileCreate, aside from that everything seems good

Comment (dynamic11) [reply services/frontend-v3/src/pages/ProfileEdit.jsx]: done

**Review by BenJeau — APPROVED** [review]
