### PR TITLE
[Fix] edit toggles missing for exfeeder card

### LINKED ISSUE #816: When viewing own profile, the visibility toggle for ex-feeder is not present
**Describe the bug**
The visibility toggle for the ex-feeder card is not present when viewing your profile (title pretty self explanatory)

**To Reproduce**
1. Go to 'My profile'
2. Scroll down to 'Ex-feeder' section
3. See that the toggle is not present

**Expected behavior**
The user should be able to toggle their own cards

**Screenshots**
image

**Additional context**
Introduced by #814 (I think)

### PR DESCRIPTION
**Pull request by dynamic11**
#### Changes introduced
- This fix brings back the edit button and visibility toggle on user profile. 
- issue was introduced by #814 

#### Related issue(s)
closes #816 

#### Screenshots (if applicable)

image

#### Checklist
If the database has been modified:
- [ ] Update database diagram 
- [ ] Create new migration 

If API endpoints has been modified:
- [ ] Update backend documentation 
- [ ] Create/Update validators for the API endpoints 
- [ ] The API endpoints are properly secured with keycloak 

If the UI has been modified:
- [x] It is translated in both language (with no hard coded text) 
- [ ] Has been tested on IE
- [ ] The modifications are tab friendly
- [x] It is accessible

### CODE REVIEW

**Review by BenJeau — APPROVED** [review]
Works great :+1: LGTM

File: services/frontend-v3/src/components/exFeeder/ExFeeder.jsx [hunk 1]
```diff
@@ -4,27 +4,29 @@ import ExFeederView from "./ExFeederView";
...
       titleId={<ExFeederView data={data} />}
       cardName="exFeeder"
       editUrl="/profile/edit/personal-growth?tab=ex-feeder"
       id="card-profile-ex-feeder"
       data={data}
-      type={type}
+      editableCardBool={editableCardBool}
       visibility={data.visibleCards.exFeeder}
+      editableCardBool={editableCardBool}
+      visibility={data.visibleCards.education}
```
Comment (BenJeau) [inline services/frontend-v3/src/components/exFeeder/ExFeeder.jsx]: Wait, you mapped the visibility to the visibleCards.education?

Comment (dynamic11) [reply services/frontend-v3/src/components/exFeeder/ExFeeder.jsx]: fixed i forgot to clean it up
