### PR TITLE
[Fix] Advanced Search for Skills

### LINKED ISSUE #153: Advanced searching with skills doesnt return results
**Describe the bug**
When searching for skills via the advanced search on the home page or in the sidebar for the results page, no results are returned even if there are profiles matching the skill search.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to homepage of I-Talent
2. Search for a skill that is on a profile in the system in the advanced search (ex: java) 
3. Sends user to results page with no results

**Expected behaviour**
Should be returning cards with matching users to search criteria, including the tags of the relevant skills on the profile cards

### PR DESCRIPTION
**Pull request by KateAThornley**
- Fixed typo on privateinfo skills which blocked skills from being returned to search

### CODE REVIEW

File: services/frontend-v3/src/components/resultsCard/ResultsCard.jsx [hunk 1]
```diff
@@ -25,14 +25,12 @@ function ResultsCard(props) {
       let queryString = urlSections[1];
       axios
         .get(backendAddress + "api/search/fuzzySearch?" + queryString)
-        .then(result => setResults(result.data));
-      // gatherResults(queryString);
+        .then((result) => setResults(result.data));
+      //gatherResults(queryString);
```
Comment (dynamic11) [inline services/frontend-v3/src/components/resultsCard/ResultsCard.jsx]: should we remove comment?

File: services/backend/API/search/util/skillSearch.js [hunk 2]
```diff
@@ -1,10 +1,11 @@
 const skillSearch = async (profiles, skillarray) => {
+  console.log("AHHHHHHHHHHH");
```
Comment (dynamic11) [inline services/backend/API/search/util/skillSearch.js]: remove

**Review by dynamic11 — CHANGES_REQUESTED** [review]

**Review by dynamic11 — APPROVED** [review]
