### PR TITLE
[Fix] Fix bugs related to card visibility toggle

### LINKED ISSUE #1487: "public" visibility status on card broken on load broken
**Describe the bug**
The "public" status on the profile card is all caps

**To Reproduce**

1. Create profile
2. Go to profile
3. Scroll to skills
4. See the issue in the visibility dropdown

**Expected behavior**
it should show the icon and and the work "public"

**Screenshots**
image

**Additional context**

### LINKED ISSUE #1488: changing card visibility to "public" fails
**Describe the bug**
If you change visibility to public the app throws and error

**To Reproduce**

1. Create profile
2. Go to profile
3. Scroll to "official languages"
4. change from private to public
5. see errors

**Expected behavior**
it should save without error

**Screenshots**
image

### LINKED ISSUE #1489: if card visibility change fails it display both a success message and an error
**Describe the bug**
if card visibility change fails it display both a success message and an error

**Screenshots**
image

### LINKED ISSUE #1490: error message in popup not translated
**Describe the bug**
error message in popup not translated

**Expected behavior**
it should have a string and not just show translation key

**Screenshots**
image

### PR DESCRIPTION
**Pull request by dynamic11**
#### ⭐ Changes introduced
This PR fixes several bugs related to the the visibility toggle on the profile cards:
- fixes the "public" status not displaying correctly due to typo in CASE statement
- fixes the bug that shows the success notification even thought the visibility change failed
- fix the bug in the translation of the error message

#### 🔗 Related issue(s)
fixes #1487
fixes #1488 
fixes #1489 
fixes #1490

#### 📸 Screenshots (if applicable)
public status displaying correctly:
image
Error message corrected:
image

#### ☑️ Checklist
If the UI has been modified:

- [ ] It is translated in both language (with no hard coded text) 
- [ ] The modifications are tab friendly
- [ ] It is accessible

If translations have been modified:

- [ ] run `yarn i18n:validate" and clear errors

### CODE REVIEW

File: services/frontend/src/components/cardVisibilityToggle/CardVisibilityToggleView.jsx [hunk 1]
```diff
@@ -52,7 +90,7 @@ const CardVisibilityToggleView = ({ status, handleVisibilityToggle, type }) => {
   const handleVisibilityPublicOk = () => {
     handleVisibilityToggle("PUBLIC");
     setModalVisibility(false);
-    openNotification();
+    // openNotification();
```
Comment (Rizvida1) [inline services/frontend/src/components/cardVisibilityToggle/CardVisibilityToggleView.jsx]: Did you mean to leave this in?

**Review by Rizvida1 — CHANGES_REQUESTED** [review]

File: services/frontend/src/components/cardVisibilityToggle/CardVisibilityToggleView.jsx (hunk 1 above)
Comment (dynamic11) [reply services/frontend/src/components/cardVisibilityToggle/CardVisibilityToggleView.jsx]: fixed

**Review by Rizvida1 — APPROVED** [review]
