### PR TITLE
[Fix] Official language save

### LINKED ISSUE #1470: Official languages save fails
**Describe the bug**
If you fill in the language form as in the screenshot and try to save you will see it fail to save with strange error

image

### PR DESCRIPTION
**Pull request by mo-5**
#### ⭐ Changes introduced

make status required

#### 🔗 Related issue(s)

closes #1470
#### ☑️ Checklist

If the database has been modified:

- [ ] Update database diagram 
- [ ] Create new migration 

If API endpoints has been modified:

- [ ] Update backend documentation 
- [ ] Create/Update validators for the API endpoints 
- [ ] The API endpoints are properly secured with keycloak

If the UI has been modified:

- [ ] It is translated in both language (with no hard coded text) 
- [ ] The modifications are tab friendly
- [ ] It is accessible

If translations have been modified:

- [ ] run `yarn i18n:validate" and clear errors

### CODE REVIEW

File: services/frontend/src/components/profileForms/langProficiencyForm/LangProficiencyFormView.jsx [hunk 1]
```diff
@@ -293,6 +293,7 @@ const LangProficiencyFormView = ({
         <Form.Item
           name={statusName}
           label={<FormattedMessage id="lang.status" />}
+          rules={[Rules.required]}
```
Comment (dynamic11) [inline services/frontend/src/components/profileForms/langProficiencyForm/LangProficiencyFormView.jsx:297]: can you add aria-required="true" to the input for accessibility. You can go to PrimaryInfoFormView.jsx for an example

**Review by dynamic11 — CHANGES_REQUESTED** [review]
please see my comments about a11y

File: services/frontend/src/components/profileForms/langProficiencyForm/LangProficiencyFormView.jsx (hunk 1 above)
Comment (mo-5) [reply services/frontend/src/components/profileForms/langProficiencyForm/LangProficiencyFormView.jsx:297]: is aria-required only for input tags ? I was wondering because I cant find it used in Select tags https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-required_attribute

Comment (dynamic11) [reply services/frontend/src/components/profileForms/langProficiencyForm/LangProficiencyFormView.jsx:297]: I used it it on the primary info form and i tested with the screen reader and it is working. we just need the screen reader to pick up the "is required"

**Review by dynamic11 — APPROVED** [review]
looks good :)
