### PR TITLE
[Fix] The ability to bypass step 2 via the url

### LINKED ISSUE #1543: profile setup can be bypassed using url
**Describe the bug**
you can jump to any step using the URL even if the contact info is not fill out

**To Reproduce**

1. Go to 'create profile'
2. Click on 'contact information'
3. replace url with "http://localhost:3000/profile/create/step/7"
4. See the steps bypass

**Expected behavior**
it should redirect back to step 1: "contact information"

### PR DESCRIPTION
**Pull request by mo-5**
#### ⭐ Changes introduced

This will prevent the user from bypassing step 2 via URL once they reach step 3 they will be able to go to any step. I changed quite a few things with the routing so please test it out and let me know if you notice anything breaking.

#### 🔗 Related issue(s)

closes #1543

#### ☑️ Checklist

If the database has been modified:

- [ ] Update database diagram 
- [ ] Create new migration 

If API endpoints has been modified:

- [ ] Update backend documentation 
- [ ] Create/Update validators for the API endpoints 
- [ ] The API endpoints are properly secured with keycloak

If the UI has been modified:

- [ ] It is translated in both language (with no hard coded text) 
- [ ] The modifications are tab friendly
- [ ] It is accessible

If translations have been modified:

- [ ] run `yarn i18n:validate" and clear errors

### CODE REVIEW

File: services/frontend/src/components/profileForms/primaryInfoForm/PrimaryInfoFormView.jsx [hunk 1]
```diff
@@ -40,6 +40,8 @@ import FormSubTitle from "../formSubTitle/FormSubTitle";
 import login from "../../../utils/login";
 
 import "./PrimaryInfoFormView.less";
+import store from "../../../redux";
+import { setUserSignupStep } from "../../../redux/slices/userSlice";
```
Comment (dynamic11) [inline services/frontend/src/components/profileForms/primaryInfoForm/PrimaryInfoFormView.jsx]: import these above the *.less file

**Review by dynamic11 — CHANGES_REQUESTED** [review]
I tested the change and it seems to be working well. Just one formatting comment

File: services/frontend/src/components/profileForms/primaryInfoForm/PrimaryInfoFormView.jsx (hunk 1 above)
Comment (mo-5) [reply services/frontend/src/components/profileForms/primaryInfoForm/PrimaryInfoFormView.jsx]: done

**Review by dynamic11 — APPROVED** [review]
