### PR TITLE
[Fix] Refactor all profile cards for improved a11y and clean up

### LINKED ISSUE #1376: Fix accessibility issue on Profile page
**Describe the bug**
Fix accessibility issues with the Profile pages.

**Expected behavior**

- [ ] Axe extensions should show no more errors or structure issues.
- [x] App should be compatible with screen readers

### LINKED ISSUE #1563: investigate the code logic for mentorship skills
**Describe the bug**
the profile card for mentorship does not have any comments and the logic seems to be unclear (line 63 specifically). It should be in vestigated

### LINKED ISSUE #1564: profile cards do not have any comments
**Describe the bug**
the profile cards have many functions that are not commented

### LINKED ISSUE #1676: If no dev goals are added but there are supporting documents then the profile page display incorrectly
**Describe the bug**
If no dev goals are added but there are supporting documents then the profile page display incorrectly

**To Reproduce**

1. delete all dev goals from profile
2. add supporting documents
3. go to profile and see the mistake

**Expected behavior**
it should only display the empty message if there are "no goal" and "no documents"

**Screenshots**
image

### PR DESCRIPTION
**Pull request by dynamic11**
#### ⭐  Changes introduced
- Reorganized heading structure for profile page (a11y)
- Refactor "Skills Card" and "Mentorship Card" to use correct headings for skill categories (a11y)
- Refactor "Dev Goals Card" to add heading for supporting documents (a11y)
- Fixed bug in "Dev Goals Card" that shoed empty card message even though supporting docs were present (bug)
- Refactor "Education Card" Items to a have a more accessible layout (a11y)
- Refactor "Experience Card" Items to a have a more accessible layout (a11y)
- Refactor "Qualified Pools Card" to a have a more accessible layout (a11y)
- Refactor "Talent Management Card" to a have a more accessible layout (a11y)
- Refactor "Job Mobility Card" to a have a more accessible layout (a11y)
- Added "empty message" for "About Me Card" (a11y)
- Redirect links on the profile page now all tell the screen reader they will redirect (a11y)
- Improved JS Docs for profile cards (documentation)
- Updated Profile Card filenames to be more descriptive (documentation)

#### 🔗 Related issue(s)
closes #1376
closes #1563
closes #1689 
closes #1564 
closes #1676 

#### 📸 Screenshots (if applicable)
The entire profile page as been slightly polish and modified

#### ☑️ Checklist

If the UI has been modified:
- [x] It is translated in both language (with no hard coded text) 
- [x] The modifications are tab friendly
- [x] It is accessible

If translations have been modified:
- [x] run `yarn i18n:validate" and clear errors

### CODE REVIEW

File: services/frontend/src/components/officialLanguageCard/OfficialLanguageCard.jsx [hunk 1]
```diff
@@ -15,7 +15,7 @@ const OfficialLanguage = ({ data, editableCardBool }) => {
    * @return {Array.<{description: String, title: String}>} - array of first language results
```
Comment (P4ul1029) [inline services/frontend/src/components/officialLanguageCard/OfficialLanguageCard.jsx]: Should change the description and `@return` line to reflect that the function now returns an object instead of an array of first language results.

File: services/frontend/src/components/educationCard/EducationCardView.jsx [hunk 2]
```diff
@@ -0,0 +1,119 @@
...
+          <FormattedMessage id="description" />
+        </h5>
+        {text}
+      </div>
+    );
+
+  /**
+   * Generate the supporting document links for the developmental goals
+   * @param {object} SupportingLinks - Object describing the supporting documents
+   * @param {string} SupportingLinks.id - Unique id the document
```
Comment (P4ul1029) [inline services/frontend/src/components/educationCard/EducationCardView.jsx]: Did you mean `Unique id of the document` in this comment?

File: services/frontend/src/components/experienceCard/ExperienceCardView.jsx [hunk 3]
```diff
@@ -0,0 +1,161 @@
...
+          <FormattedMessage id="description" />
+        </h5>
+        {text}
+      </div>
+    );
+
+  /**
+   * Generate the supporting document links for the developmental goals
+   * @param {object} SupportingLinks - Object describing the supporting documents
+   * @param {string} SupportingLinks.id - Unique id the document
```
Comment (P4ul1029) [inline services/frontend/src/components/experienceCard/ExperienceCardView.jsx]: Did you mean `Unique id of the document` in this comment?

File: services/frontend/src/components/learningDevelopment/LearningDevelopmentView.jsx [hunk 4]
```diff
@@ -1,62 +1,97 @@
...
-              description={<FormattedMessage id="developmental.goals.empty" />}
-              image={Empty.PRESENTED_IMAGE_SIMPLE}
+  /**
+   * Generate the supporting document links for the developmental goals
+   * @param {object} SupportingLinks - Object describing the supporting documents
+   * @param {string} SupportingLinks.id - Unique id the document
+   * @param {string} SupportingLinks.url - URL to the document
+   * @param {object} SupportingLinks.name - Object describing of the document type
+   * @param {object} SupportingLinks.name.name - Translated name of the document type
+   * @param {string} SupportingLinks.name.id - Unique id the document type
```
Comment (P4ul1029) [inline services/frontend/src/components/learningDevelopment/LearningDevelopmentView.jsx:45]: Did you mean `Unique id of the document` in line 41 and 45?

**Comment by P4ul1029** [comment]
I switched onto this branch and editted all the aspects of my profile and ran into no issues.

When I tried to view a mock user's profile though, I ran into issue #1682:
image
Should this be fixed in this PR or a future one?

**Review by P4ul1029 — CHANGES_REQUESTED** [review]
See comments above.

**Comment by dynamic11** [comment]
> I switched onto this branch and editted all the aspects of my profile and ran into no issues.
> 
> When I tried to view a mock user's profile though, I ran into issue #1682: image Should this be fixed in this PR or a future one?

I cant reproduce this bug...

**Review by Rizvida1 — APPROVED** [review]
Works well for me

**Review by P4ul1029 — APPROVED** [review]
LGTM!
