### PR TITLE
[Fix] improve a11y of footer and "bug report" modal

### LINKED ISSUE #1521: [Perfective] External Link Accessibility
### [Perfective] External Link Accessibility
When a link opens a new tab, the screen reader should inform the user that it will open in a new tab.

**Issue Location:** 
- Landing Page
- Create Profile: Welcome Form
- Create Profile: Contact Information Form
- Edit Profile: Contact Information Form

**Steps to recreate:**
- Navigate to any one of these pages and go to the bottom 
- There will be the following links: About I-Talent|Help/Contact Us|Terms and conditions|Privacy
- With the screen reader, focus on any of these fields. It does not inform the user that they will open in a new tab

Justification: The objective of this technique is to provide a warning before automatically opening a new window or tab. Opening new windows automatically when a link is activated can be disorienting for people who have difficulty perceiving visual content, and for some people with cognitive disabilities. FYI It is also possible to add a small "external link" icon to the link (this is just extra info, I am not saying it needs to be implemented)
external links

### LINKED ISSUE #1671: radio group in feedback form not a11y compliant
**Describe the bug**
The radio button group in the feedback modal is not screen reader friendly
should be replaced with dropdown

**To Reproduce**

1. Go to app footer
2. Click on 'report a bug'
3. Scroll down to tab to radio group
4. See screen reader not working correctly

**Expected behavior**
It should read all the options

**Screenshots**
image

### PR DESCRIPTION
**Pull request by dynamic11**
#### ⭐ Changes introduced
- restyle "report bug" button to make it less distracting
- added support for screen reader to say "opens in a new tab" when footer links are highlighted
- replaced radio group with dropdown to improve screen reader performance
- clean up code and commenting

#### 🔗 Related issue(s)
closes #1521 
closes #1671 

#### 📸 Screenshots (if applicable)
image
image

#### ☑️ Checklist

If the UI has been modified:
- [x] It is translated in both language (with no hard coded text) 
- [x] The modifications are tab friendly
- [x] It is accessible

If translations have been modified:
- [x] run `yarn i18n:validate" and clear errors

### CODE REVIEW

File: services/frontend/src/components/reportBug/ReportBugView.jsx [hunk 1]
```diff
@@ -143,22 +141,32 @@ const ReportBugView = ({ saveDataToDB }) => {
 
         <Form form={form} layout="vertical" onFieldsChange={onFormValuesChange}>
           <Form.Item
+            id="gg"
```
Comment (Rizvida1) [inline services/frontend/src/components/reportBug/ReportBugView.jsx]: Is this a descriptive ID?

File: services/frontend/src/components/reportBug/ReportBugView.jsx [hunk 2]
```diff
@@ -143,22 +141,32 @@ const ReportBugView = ({ saveDataToDB }) => {
...
             name="location"
             rules={[Rules.required]}
           >
-            <Radio.Group
+            {/* <Radio.Group
+              aria-required="true"
               buttonStyle="solid"
               options={radioOptions}
               optionType="button"
+            /> */}
```
Comment (Rizvida1) [inline services/frontend/src/components/reportBug/ReportBugView.jsx]: Should this stay?

**Review by Rizvida1 — CHANGES_REQUESTED** [review]

**Review by Rizvida1 — APPROVED** [review]
