### PR TITLE
[Fix] improve accessibility of privacy modal

### LINKED ISSUE #1484: Screen reader behaves strangely when opening privacy modal
**Describe the bug**
On the privacy modal opens the screen reader:
- keeps repeating the description of the translation button in the modal header
- keeps reading the icons

**To Reproduce**

1. Login to app
2. see the privacy modal that automatically opens

**Expected behavior**
The screen reader should only read the modal title and skip reading the icons

### PR DESCRIPTION
**Pull request by dynamic11**
#### ⭐ Changes introduced
- moved the "change language button" to footer of privacy modal to stop screen reader from reading it repeatedly when the modal opens
- hid all the icons in the modal from the screen reader

#### 🔗 Related issue(s)
closes #1484 

#### 📸 Screenshots (if applicable)
image

#### ☑️ Checklist

If the UI has been modified:

- [x] It is translated in both language (with no hard coded text) 
- [x] The modifications are tab friendly
- [x] It is accessible

If translations have been modified:

- [x] run `yarn i18n:validate" and clear errors

### CODE REVIEW

File: services/frontend/src/components/privacyModal/PrivacyModalView.jsx [hunk 1]
```diff
@@ -9,30 +9,41 @@ const PrivacyModalView = ({ handleOk, handleCancel, showModal, locale }) => (
...
+    //     <CheckOutlined className="ModalbBtnIcon" aria-hidden="true" />
+    //     <FormattedMessage id="privacy.modal.accept" />
+    //   </>
+    // }
+    // cancelText={
+    //   <>
+    //     <CloseOutlined className="ModalbBtnIcon" aria-hidden="true" />
+    //     <FormattedMessage id="privacy.modal.decline" />
+    //   </>
+    // }
```
Comment (Rizvida1) [inline services/frontend/src/components/privacyModal/PrivacyModalView.jsx]: Did you mean to leave this in?

**Review by Rizvida1 — CHANGES_REQUESTED** [review]

**Review by Rizvida1 — APPROVED** [review]

**Comment by MenaMachado** [comment]
Approved

**Review by MenaMachado — APPROVED** [review]
