### PR TITLE
[Fix] improve screen reader a11y of confirmation modals

### LINKED ISSUE #1475: Save changes modal is not screen reader accessible.
**Describe the bug**
the screen reader does not read the content of the modal

**To Reproduce**

1. Go to any edit profile form
2. Make an edit
3. clock on any other form without saving
4. See the modal that pops up

**Expected behavior**
The screen reader should read the content of every modal. If we use another type of antd modal it should fix this issue

**Screenshots**
image

**Additional context**

### LINKED ISSUE #1492: investigate to remove material ui modal
**Describe the bug**
if antd modal is accessible then investigate removing the material ui one in the visibility toggle

**Screenshots**
image

### LINKED ISSUE #1652: danger button doesn't pass a11y color contrast test
**Describe the bug**
It should pass a11y AA standard

**Screenshots**
image

### PR DESCRIPTION
**Pull request by dynamic11**
#### ⭐ Changes introduced
- improve contrast for danger color for a11y
- make confirmation modal for "public visibility" screen reader compliant
- make confirmation modal for "delete profile" screen reader compliant
- make confirmation modal for "skip setup" screen reader compliant
- remove matrial-ui modal

⚠️ working with NVDA and not with Windows narrator

#### 🔗 Related issue(s)
closes #1492 
closes #1475 
closes #1652 

#### 📸 Screenshots (if applicable)
image
image
image

#### ☑️ Checklist

If the UI has been modified:
- [x] It is translated in both language (with no hard coded text) 
- [x] The modifications are tab friendly
- [x] It is accessible

If translations have been modified:
- [x] run `yarn i18n:validate" and clear errors

### CODE REVIEW

File: services/frontend/src/components/cardVisibilityToggle/CardVisibilityToggleView.jsx [hunk 1]
```diff
@@ -77,33 +76,46 @@ const CardVisibilityToggleView = ({
   };
 
   /**
-   * Handel selection change in drop down
-   * open modal confirmation if "public" is selected
-   * @param {Object} value - value selected from dropdown
+   * Handel public visibility confirmation
```
Comment (Rizvida1) [inline services/frontend/src/components/cardVisibilityToggle/CardVisibilityToggleView.jsx:79]: Spelling?

**Review by Rizvida1 — APPROVED** [review]
