### PR TITLE
[Fix] Merged skill and mentorship tabs

### LINKED ISSUE #1598: When a user deletes a skill in their profile it should also automatically delete from the mentorship skill
After a user deletes a skill, currently the skill is showing up as an ID under mentorship and the user need to delete it. 

When a user deletes a skill in their profile it should  also automatically be deleted from the mentorship skill, if applicable

Below is an example of an ID after I deleted Collaboration: Stakeholder Engagement.

image

image

### PR DESCRIPTION
**Pull request by Rizvida1**
#### ⭐ Changes introduced

Merged the mentorship skill tab into the skill tab.

#### 🔗 Related issue(s)

Fixes #1598

#### 📸 Screenshots (if applicable)

image

#### ☑️ Checklist

If the UI has been modified:

- [X] It is translated in both language (with no hard coded text) 
- [X] The modifications are tab friendly
- [X] It is accessible

If translations have been modified:

- [X] run `yarn i18n:validate" and clear errors

### CODE REVIEW

File: services/frontend/src/components/profileForms/talentForm/TalentFormView.jsx [hunk 1]
```diff
@@ -479,11 +459,35 @@ const TalentFormView = ({
...
+    updateIfFormValuesChanged();
+    setTabErrorsBool([]);
+  };
+
   /*
    * Get mentorship form
    *
    * Get mentorship role form based on if the form switch is toggled
    */
+
```
Comment (dynamic11) [inline services/frontend/src/components/profileForms/talentForm/TalentFormView.jsx]: remove extra space

**Review by dynamic11 — APPROVED** [review]
