### PR TITLE
[Fix] Add regex rules to firstName and lastName in form

### LINKED ISSUE #617: Users are able to enter any character for first and last name
**Describe the bug**
1. user can provide any first and last name.  You are able to change your name to anything including a space or numbers

**To Reproduce**
- Navigate to My Profile -> General Profile Info -> Edit Profile

**Expected behavior**
We should set some rules for first and last name. 

**Describe the bug**

2. Note that your profile name and picture does not update with these changes

**To Reproduce**
- Navigate to My Profile -> General Profile Info -> Edit Profile
- Change Name
- Save and Finish

image

### PR DESCRIPTION
**Pull request by BenJeau**
### Changes
- Added regex for firstName and lastName to accent only valid characters, and if a "-" is present, it needs to be surrounded by letters
- Capitalize firstName and lastName in the backend before saving to the database
- Get name from database to display in the dropdown

fixes #617

### CODE REVIEW

File: services/backend/src/core/profile/profile.js [hunk 1]
```diff
@@ -27,6 +27,10 @@ function idHelper(id, savedId) {
   };
 }
 
+function capitalizeFirstLetter(string) {
+  return string.charAt(0).toUpperCase() + string.slice(1);
```
Comment (mo-5) [inline services/backend/src/core/profile/profile.js]: Should we just use lodash here since its already imported? _.upperFirst

File: services/backend/src/core/user/user.js [hunk 2]
```diff
@@ -67,6 +67,10 @@ async function getUserById(request, response) {
   }
 }
 
+function capitalizeFirstLetter(string) {
+  return string.charAt(0).toUpperCase() + string.slice(1);
```
Comment (mo-5) [inline services/backend/src/core/user/user.js]: Same here

File: services/backend/src/core/profile/profile.js [hunk 3]
```diff
@@ -204,8 +208,8 @@ async function updateProfile(request, response) {
       await prisma.user.update({
         where: { id: userId },
         data: {
-          firstName,
-          lastName,
+          firstName: firstName ? capitalizeFirstLetter(firstName) : undefined,
```
Comment (mo-5) [inline services/backend/src/core/profile/profile.js]: If we set it to undefined wouldnt that erase the name from the db ?

Comment (BenJeau) [reply services/backend/src/core/profile/profile.js]: No, it would just act as there would be no variable there. If its null, it will make it null in the db

File: services/backend/src/core/profile/profile.js (hunk 1 above)
Comment (BenJeau) [reply services/backend/src/core/profile/profile.js]: Ohh didn't know there was a lodash function for that... will make the change

**Review by mo-5 — APPROVED** [review]
