### PR TITLE
[Fix] Code duplication, security hotspot, and simplify code logic 

### LINKED ISSUE #969: Frontend code smell
https://sonarqube-ised-ci.apps.dev.openshift.ised-isde.canada.ca/project/issues?id=ITalent-frontend&resolved=false&sinceLeakPeriod=true&types=CODE_SMELL

### PR DESCRIPTION
**Pull request by mo-5**
#### Changes introduced

- Rewrite some components to remove code duplication and simplify the logic.
- Fixed security hotspot
#### Related issue(s)

closes #969 , #967

#### Checklist
If the database has been modified:
- [ ] Update database diagram 
- [ ] Create new migration 

If API endpoints has been modified:
- [ ] Update backend documentation 
- [ ] Create/Update validators for the API endpoints 
- [ ] The API endpoints are properly secured with keycloak 

If the UI has been modified:
- [ ] It is translated in both language (with no hard coded text) 
- [ ] Has been tested on IE
- [ ] The modifications are tab friendly
- [ ] It is accessible

### CODE REVIEW

**Comment by mo-5** [comment]
Could I please get this checked and merged I want to see if sonarqube will update the information

File: services/frontend/src/components/admin/categoryTable/CategoryTableView.jsx [hunk 1]
```diff
@@ -111,8 +111,9 @@ const CategoryTableView = ({
     filterIcon: (filtered) => (
       <SearchOutlined style={{ color: filtered ? "#1890ff" : undefined }} />
     ),
-    onFilter: (value, record) =>
-      record[dataIndex].toString().toLowerCase().includes(value.toLowerCase()),
+    onFilter: (value, record) => {
+      record[dataIndex].toString().toLowerCase().includes(value.toLowerCase());
+    },
```
Comment (BenJeau) [inline services/frontend/src/components/admin/categoryTable/CategoryTableView.jsx]: This function needs to return a boolean (https://ant.design/components/table/#Column) or else it won't filter the column

File: services/frontend/src/components/admin/categoryTable/CategoryTableView.jsx [hunk 2]
```diff
@@ -132,7 +133,7 @@ const CategoryTableView = ({
   });
 
   /* Renders the success message on top of page */
-  const popUpSuccesss = () => {
+  const popUpSuccesses = () => {
```
Comment (BenJeau) [inline services/frontend/src/components/admin/categoryTable/CategoryTableView.jsx]: Should it just be `popUpSuccess`?

File: services/frontend/src/components/admin/skillTable/SkillTable.jsx [hunk 3]
```diff
@@ -24,52 +24,35 @@ const SkillTable = ({ intl }) => {
...
+        );
+        dispatch(
+          setAdminCategories(
+            categories.data.map((category) => ({
+              ...category,
+              key: category.id,
+            }))
+          )
+        );
+      });
```
Comment (BenJeau) [inline services/frontend/src/components/admin/skillTable/SkillTable.jsx]: since we are using catch the async way, not the promise way here, could we maybe use awaits so its less nested?

```suggestion
      const [skill, categories] = await Promise.all([
        axios.get(`api/option/skillsAllLang`),
        axios.get(`api/option/categoriesAllLang`),
      ]);
      
      dispatch(
        setAdminSkills(
          skill.data.map((category) => ({ ...category, key: category.id }))
        )
      );
      
      dispatch(
        setAdminCategories(
          categories.data.map((category) => ({
            ...category,
            key: category.id,
          }))
        )
      );
```

File: services/frontend/src/components/errorResult/errorPage.jsx [hunk 4]
```diff
@@ -5,9 +5,8 @@ import { FormattedMessage } from "react-intl";
 import { HomeOutlined } from "@ant-design/icons";
 import ErrorResultView from "./errorResultView";
 
-const Error403 = () => {
+const ErrorPage = (error) => {
```
Comment (BenJeau) [inline services/frontend/src/components/errorResult/errorPage.jsx]: Maybe rename the error to errorNumber? Also you are using the whole props here and I don't think that is what you meant to do. You will also need to add some propTypes to this component

```suggestion
const ErrorPage = ({ error }) => {
```

File: services/frontend/src/components/errorResult/errorProfilePage.jsx [hunk 5]
```diff
@@ -6,7 +6,7 @@ import { HomeOutlined, UserOutlined } from "@ant-design/icons";
 import { useSelector } from "react-redux";
 import ErrorResultView from "./errorResultView";
 
-const ErrorProfileHidden = () => {
+const ErrorProfilePage = (title, subtitle) => {
```
Comment (BenJeau) [inline services/frontend/src/components/errorResult/errorProfilePage.jsx]: Same situation as above, and add PropTypes. Since the "title" and "subtitle" prop is technically not the title/subtitle, can you rename it to something related to the formattedMessage, maybe titleId and subtitleId?

```suggestion
const ErrorProfilePage = ({ title, subtitle }) => {
```

File: services/frontend/src/components/layouts/aboutLayout/AboutLayoutView.jsx [hunk 6]
```diff
@@ -27,78 +27,32 @@ const AboutLayoutView = ({ type }) => {
     return <Redirect to="/" />;
   }
 
+  const tabPaneSetting = (key, name) => {
```
Comment (BenJeau) [inline services/frontend/src/components/layouts/aboutLayout/AboutLayoutView.jsx]: Same here, maybe rename "name" to nameId?

File: services/frontend/src/components/profileForms/employmentDataForm/EmploymentDataForm.jsx [hunk 7]
```diff
@@ -31,66 +31,31 @@ const EmploymentDataForm = ({ formType }) => {
...
+    try {
+      return await Promise.all([
+        axios.get(`api/option/tenures?language=${locale}`),
+        axios.get(`api/option/classifications?language=${locale}`),
+        axios.get(`api/option/securityClearances?language=${locale}`),
+        axios.get(`api/profile/private/${id}?language=${locale}`),
+      ]);
+    } catch (error) {
+      handleError(error, "redirect", history);
+      throw error;
```
Comment (BenJeau) [inline services/frontend/src/components/profileForms/employmentDataForm/EmploymentDataForm.jsx]: In the getBackendInfo from one of the component above, you are setting the state inside of it, should it be the same here?

File: services/frontend/src/components/profileForms/primaryInfoForm/gedsUpdateModal/GedsUpdateModalView.jsx [hunk 8]
```diff
@@ -145,6 +145,7 @@ const GedsUpdateModalView = ({ visibility, saveDataToDB }) => {
   const syncGedsButtonAction = async ({ paramName }) => {
     setTableLoading(true);
 
+    // eslint-disable-next-line prefer-const
     let updatedProfile = {};
```
Comment (BenJeau) [inline services/frontend/src/components/profileForms/primaryInfoForm/gedsUpdateModal/GedsUpdateModalView.jsx]: Why not converting this to a const? In js, a const just means you can set, in this case, updateProfile to a new value, but you can technically still update its object values

File: services/frontend/src/pages/admin/AdminDashboard.jsx [hunk 9]
```diff
@@ -151,34 +48,56 @@ const AdminDashboard = ({ intl }) => {
...
+        axios.get(`api/stats/count/users`),
+        axios.get(`api/stats/count/hiddenUsers`),
+        axios.get(`api/stats/count/inactiveUsers`),
+        axios.get(`api/stats/count/exFeederUsers`),
+        axios.get(`api/stats/growthRateByMonth`),
+        axios.get(`api/stats/growthRateByWeek`),
+        axios.get(`api/stats/topFiveCompetencies?language=${locale}`),
+        axios.get(`api/stats/topFiveDevelopmentalGoals?language=${locale}`),
+        axios.get(`api/stats/topFiveSkills?language=${locale}`),
+      ]);
```
Comment (BenJeau) [inline services/frontend/src/pages/admin/AdminDashboard.jsx]: Same as above, 
```suggestion
      const [users, hiddenUsers, inactiveUsers, exFeederUsers, growthRateByMonth, growthRateByWeek, ....] =  await Promise.all([
        axios.get(`api/stats/count/users`),
        axios.get(`api/stats/count/hiddenUsers`),
        axios.get(`api/stats/count/inactiveUsers`),
        axios.get(`api/stats/count/exFeederUsers`),
        axios.get(`api/stats/growthRateByMonth`),
        axios.get(`api/stats/growthRateByWeek`),
        axios.get(`api/stats/topFiveCompetencies?language=${locale}`),
        axios.get(`api/stats/topFiveDevelopmentalGoals?language=${locale}`),
        axios.get(`api/stats/topFiveSkills?language=${locale}`),
      ]);
      
      dispatch(setCountUsers(userCount.data));
      dispatch(setCountHiddenUsers(hiddenUserCount.data));
      dispatch(setCountInactiveUsers(inactiveUserCount.data));
      dispatch(setCountExFeederUsers(exFeederUserCount.data));
      dispatch(setGrowthRateByMonth(growthRateByMonth.data));
      dispatch(setGrowthRateByWeek(growthRateByWeek.data));
```

Comment (BenJeau) [reply services/frontend/src/pages/admin/AdminDashboard.jsx]: Also feel free to modify the actions in redux, so instead of dispatching 9 seperate times to the redux store, you could do it in one batch, it would clean up the code here and the code in the redux admin slice

File: services/frontend/src/pages/Stats.jsx [hunk 10]
```diff
@@ -18,62 +18,34 @@ const Stats = () => {
   const intl = useIntl();
   const history = useHistory();
 
-  const getTopFiveCompentencies = useCallback(async () => {
+  const getBackendInfo = useCallback(async () => {
```
Comment (BenJeau) [inline services/frontend/src/pages/Stats.jsx:17]: Same advice here

File: services/frontend/src/components/searchFilter/SearchFilter.jsx [hunk 11]
```diff
@@ -58,83 +58,69 @@ const SearchFilter = () => {
...
     setAnyMentorSkills(e.target.checked);
   };
 
-  useEffect(() => {
-    // Fetches options for skills select field in advanced search
-    const getSkills = async () => {
-      const [categoriesResult, skillsResults] = await Promise.all([
+  const getBackendInfo = useCallback(async () => {
+    try {
+      return await Promise.all([
```
Comment (BenJeau) [inline services/frontend/src/components/searchFilter/SearchFilter.jsx]: Same advice here (with the array decomposition)

File: services/frontend/src/components/layouts/createProfileLayout/CreateProfileLayoutView.jsx [hunk 12]
```diff
@@ -81,6 +81,28 @@ const CreateProfileLayoutView = ({ formStep, highestStep }) => {
...
+        <li>
+          <FormattedMessage id={description} />
+        </li>
+      );
+    });
+    return modifiedDescriptions ? (
+      <ul className="stepList">{modifiedDescriptions}</ul>
+    ) : undefined;
+  };
+  const createProfileStep = (titleId, descriptions, disabled) => {
```
Comment (BenJeau) [inline services/frontend/src/components/layouts/createProfileLayout/CreateProfileLayoutView.jsx]: Maybe add some brief JSDoc to these functions

**Review by BenJeau — COMMENTED** [review]
This PR looks good, a good cleanup, just a few comments and I'll test it afterwards

File: services/frontend/src/components/profileForms/primaryInfoForm/gedsUpdateModal/GedsUpdateModalView.jsx (hunk 8 above)
Comment (MohamedRadwan) [reply services/frontend/src/components/profileForms/primaryInfoForm/gedsUpdateModal/GedsUpdateModalView.jsx:149]: The reason I made it let is that with const every time we change updatedProfile we are basically creating a new variable. I can change it back to const.

**Review by BenJeau — COMMENTED** [review]
Looks good, but I am seeing this 
image

not sure if its related to this change

**Comment by mo-5** [comment]
Good catch! Fixed

**Review by BenJeau — APPROVED** [review]
