### PR TITLE
[Fix] Fixed console log errors on Profile page

### LINKED ISSUE #1444: Console errors on profile page
**Describe the bug**

There are many missing keys and translation id errors on the profile page

**To Reproduce**

1. Go to profile page
2. Check logs

**Expected behavior**

There should not be any errors

### PR DESCRIPTION
**Pull request by Rizvida1**
#### ⭐ Changes introduced

Removed console errors on the profile page including:

- Missing keys error
- Missing translation id errors

#### 🔗 Related issue(s)

Fixes #1444

### CODE REVIEW

File: services/frontend/src/components/mentorshipCard/MentorshipView.jsx [hunk 1]
```diff
@@ -2,34 +2,31 @@ import PropTypes from "prop-types";
 import { Tag, Empty, Row, Col } from "antd";
 import { TagTwoTone } from "@ant-design/icons";
 import { FormattedMessage } from "react-intl";
+import { Fragment } from "react";
```
Comment (dynamic11) [inline services/frontend/src/components/mentorshipCard/MentorshipView.jsx]: please put this at the top (just a personal preference since react is the "main" package) let me know what you think

File: services/frontend/src/components/skillsCard/SkillsView.jsx [hunk 2]
```diff
@@ -2,34 +2,31 @@ import PropTypes from "prop-types";
 import { Tag, Empty, Row, Col } from "antd";
 import { TagTwoTone } from "@ant-design/icons";
 import { FormattedMessage } from "react-intl";
+import { Fragment } from "react";
```
Comment (dynamic11) [inline services/frontend/src/components/skillsCard/SkillsView.jsx]: same thing

File: services/frontend/src/components/skillsCard/SkillsView.jsx [hunk 3]
```diff
@@ -2,34 +2,31 @@ import PropTypes from "prop-types";
...
-                    {skills[categorySkill.index].val.map((skill) => (
-                      <Tag color="#00605e">{skill}</Tag>
-                    ))}
-                  </Col>
-                </Row>
-              </>
-            )
-        )}
-      </>
+    return categoriesSkills.map(
```
Comment (dynamic11) [inline services/frontend/src/components/skillsCard/SkillsView.jsx:9]: you removed the empty fragment if the map is empty. are sure this isn't going to cause issue

**Review by dynamic11 — COMMENTED** [review]
please see my comments. :)

File: services/frontend/src/components/skillsCard/SkillsView.jsx (hunk 3 above)
Comment (Rizvida1) [reply services/frontend/src/components/skillsCard/SkillsView.jsx:9]: It's only runs if there is a skill and if there is a skill, it must belong to a category, no?

File: services/frontend/src/components/experience/ExperienceView.jsx [hunk 4]
```diff
@@ -11,9 +12,9 @@ const ExperienceView = ({ experienceInfo }) => {
       return (
         <div className="bodyStyle">
           {lineStrings.map((line, index) => (
-            <>
+            <Fragment key={line}>
```
Comment (dynamic11) [inline services/frontend/src/components/experience/ExperienceView.jsx:15]: is it ok for the key to be a string with spaces? what if it is really long? I feel like it wont be efficient in terms of memory

File: services/frontend/src/components/experience/ExperienceView.jsx [hunk 5]
```diff
@@ -36,7 +37,7 @@ const ExperienceView = ({ experienceInfo }) => {
   const getProjects = (item) => {
     if (item.projects && item.projects.length > 0)
       return item.projects.map((i) => (
-        <Tag color="#727272" key={i.id}>
+        <Tag color="#727272" key={i}>
```
Comment (dynamic11) [inline services/frontend/src/components/experience/ExperienceView.jsx:40]: same comment here

**Review by dynamic11 — COMMENTED** [review]
please see new comments

File: services/frontend/src/components/experience/ExperienceView.jsx (hunk 4 above)
Comment (Rizvida1) [reply services/frontend/src/components/experience/ExperienceView.jsx:15]: According to my research, the length does not impact performance and there are examples on the antd website that have keys with spaces

File: services/frontend/src/components/skillsCard/SkillsView.jsx (hunk 3 above)
Comment (dynamic11) [reply services/frontend/src/components/skillsCard/SkillsView.jsx:9]: if it doesn't effect the behavior then im ok with it

File: services/frontend/src/components/experience/ExperienceView.jsx (hunk 4 above)
Comment (dynamic11) [reply services/frontend/src/components/experience/ExperienceView.jsx:15]: okay!

**Review by dynamic11 — APPROVED** [review]
LGTM. thank you for addressing my comments
